### ISSUE TITLE
Getting 500 Error while deleting the channels

### ISSUE THREAD

**Issue by thisissuman** [AntonioErdeljac/next13-discord-clone#32]
`○ Compiling /api/channels/[channelId]/route ...
 ✓ Compiled /api/channels/[channelId]/route in 524ms (838 modules)
[CHANNEL_ID_DELETE] PrismaClientKnownRequestError: 
Invalid `prisma.server.update()` invocation:

The records for relation `ChannelToServer` between the `Server` and `Channel` models are not connected.
    at Cn.handleRequestError (D:\Next JS\discord-clone\node_modules\@prisma\client\runtime\library.js:123:6817)
    at Cn.handleAndLogRequestError (D:\Next JS\discord-clone\node_modules\@prisma\client\runtime\library.js:123:6206)
    at Cn.request (D:\Next JS\discord-clone\node_modules\@prisma\client\runtime\library.js:123:5926)
    at async l (D:\Next JS\discord-clone\node_modules\@prisma\client\runtime\library.js:128:9968)
    at async DELETE (webpack-internal:///(rsc)/./app/api/channels/[channelId]/route.ts:34:24)
    at async D:\Next JS\discord-clone\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:61856 {
  code: 'P2017',
  clientVersion: '5.5.2',
  meta: {
    relation_name: 'ChannelToServer',
    parent_name: 'Server',
    child_name: 'Channel'
  }
}
[CHANNEL_ID_DELETE] PrismaClientKnownRequestError:
Invalid `prisma.server.update()` invocation:

The records for relation `ChannelToServer` between the `Server` and `Channel` models are not connected.
    at Cn.handleRequestError (D:\Next JS\discord-clone\node_modules\@prisma\client\runtime\library.js:123:6817)      
    at Cn.handleAndLogRequestError (D:\Next JS\discord-clone\node_modules\@prisma\client\runtime\library.js:123:6206)
    at Cn.request (D:\Next JS\discord-clone\node_modules\@prisma\client\runtime\library.js:123:5926)
    at async l (D:\Next JS\discord-clone\node_modules\@prisma\client\runtime\library.js:128:9968)
    at async DELETE (webpack-internal:///(rsc)/./app/api/channels/[channelId]/route.ts:34:24)
    at async D:\Next JS\discord-clone\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:61856 {
  code: 'P2017',
  clientVersion: '5.5.2',
  meta: {
    relation_name: 'ChannelToServer',
    parent_name: 'Server',
    child_name: 'Channel'
  }
}
`

**Comment by Triv2** [comment]
It looks like your prisma schema isn't setup properly. It says your relations between server and channel aren't connected.
